title: Your Blog Title
description: Your blog description
meta_description: "Your New Spelt Site, Blogging about stuffs"

logo: false
paginate: 15
baseurl: "/"
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'

url: 'http://example.com'
author: 'Your Name'
author_bio: "Follow me on [Twitter](https://twitter.com/username) or [GitHub](https://github.com/username)."